import { SpellEntry } from '../gameData';

export const SPELLS_DB: SpellEntry[] = [
  // NÍVEL 0 (TRUQUES)
  {
    id: "fire_bolt",
    classes: ["feiticeiro","mago"],
    name: "Raio de Fogo",
    level: 0,
    school: "Evocação",
    castingTime: "action",
    range: "36 metros",
    components: "V, S",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Você arremessa um cisco de fogo em uma criatura ou objeto. Faça um ataque à distância com magia. Em um acerto, o alvo sofre 1d10 de dano de fogo.",
    damageDice: "1d10",
    damageType: "fogo",
    spellAttack: true,
    effect: "damage",
    targetType: "single"
  },
  {
    id: "light",
    classes: ["bardo","clerigo","feiticeiro","mago"],
    name: "Luz",
    level: 0,
    school: "Evocação",
    castingTime: "action",
    range: "Toque",
    components: "V, M",
    duration: "1 hora",
    isConcentration: false,
    isRitual: false,
    description: "Você toca um objeto que não tenha mais de 3 metros. Até o fim da magia, o objeto emite luz plena num raio de 6 metros e penumbra por mais 6 metros.",
    effect: "utility",
    targetType: "single"
  },
  {
    id: "guidance",
    classes: ["clerigo","druida"],
    name: "Orientação",
    level: 0,
    school: "Adivinhação",
    castingTime: "action",
    range: "Toque",
    components: "V, S",
    duration: "1 minuto",
    isConcentration: true,
    isRitual: false,
    description: "Você toca uma criatura voluntária. Uma vez antes da magia acabar, o alvo pode rolar 1d4 e adicionar o número rolado a um teste de habilidade de sua escolha.",
    effect: "buff",
    targetType: "single"
  },
  {
    id: "mage_hand",
    classes: ["bardo","feiticeiro","mago","bruxo"],
    name: "Mãos Mágicas",
    level: 0,
    school: "Conjuração",
    castingTime: "action",
    range: "9 metros",
    components: "V, S",
    duration: "1 minuto",
    isConcentration: false,
    isRitual: false,
    description: "Uma mão espectral flutuante aparece num ponto. Você pode usar a mão para manipular objetos, abrir portas, etc.",
    effect: "utility",
    targetType: "single"
  },
  {
    id: "minor_illusion",
    classes: ["bardo","feiticeiro","mago","bruxo"],
    name: "Ilusão Menor",
    level: 0,
    school: "Ilusão",
    castingTime: "action",
    range: "9 metros",
    components: "S, M",
    duration: "1 minuto",
    isConcentration: false,
    isRitual: false,
    description: "Você cria um som ou imagem de um objeto dentro do alcance. A ilusão tem a duração de 1 minuto.",
    effect: "utility",
    targetType: "single"
  },
  {
    id: "eldritch_blast",
    classes: ["bruxo"],
    name: "Rajada Mística",
    level: 0,
    school: "Evocação",
    castingTime: "action",
    range: "36 metros",
    components: "V, S",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Um feixe de energia crepitante vai em direção a uma criatura. Em um acerto, o alvo sofre 1d10 de dano de força.",
    damageDice: "1d10",
    damageType: "forca",
    spellAttack: true,
    effect: "damage",
    targetType: "single"
  },
  {
    id: "sacred_flame",
    classes: ["clerigo"],
    name: "Chama Sagrada",
    level: 0,
    school: "Evocação",
    castingTime: "action",
    range: "18 metros",
    components: "V, S",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Chamas divinas descem sobre uma criatura que você possa ver. O alvo deve passar num teste de Destreza ou sofrerá 1d8 de dano radiante.",
    damageDice: "1d8",
    damageType: "radiante",
    savingThrow: "des",
    effect: "damage",
    targetType: "single"
  },
  {
    id: "ray_of_frost",
    classes: ["feiticeiro","mago"],
    name: "Raio de Gelo",
    level: 0,
    school: "Evocação",
    castingTime: "action",
    range: "18 metros",
    components: "V, S",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Um raio de luz azulada vai em direção à criatura. Em um acerto, sofre 1d8 dano de frio e o deslocamento dela é reduzido em 3m até o próximo turno.",
    damageDice: "1d8",
    damageType: "frio",
    spellAttack: true,
    effect: "damage",
    targetType: "single"
  },
  
  // NÍVEL 1
  {
    id: "mage_armor",
    classes: ["feiticeiro","mago"],
    name: "Armadura Arcana",
    level: 1,
    school: "Abjuração",
    castingTime: "action",
    range: "Toque",
    components: "V, S, M",
    duration: "8 horas",
    isConcentration: false,
    isRitual: false,
    description: "Você toca uma criatura voluntária que não esteja usando armadura. Até a magia acabar, a CA base do alvo se torna 13 + seu modificador de Destreza.",
    effect: "buff",
    targetType: "single"
  },
  {
    id: "shield_of_faith",
    classes: ["clerigo","paladino"],
    name: "Escudo da Fé",
    level: 1,
    school: "Abjuração",
    castingTime: "bonus",
    range: "18 metros",
    components: "V, S, M",
    duration: "10 minutos",
    isConcentration: true,
    isRitual: false,
    description: "Um campo cintilante aparece ao redor de uma criatura da sua escolha dentro do alcance, concedendo um bônus de +2 na CA durante a duração.",
    effect: "buff",
    targetType: "single"
  },
  {
    id: "healing_word",
    classes: ["bardo","clerigo","druida"],
    name: "Palavra Curativa",
    level: 1,
    school: "Evocação",
    castingTime: "bonus",
    range: "18 metros",
    components: "V",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Uma criatura à sua escolha que você possa ver, recupera 1d4 + seu modificador de habilidade de conjuração pontos de vida.",
    damageDice: "1d4",
    effect: "heal",
    targetType: "single"
  },
  {
    id: "shield",
    classes: ["feiticeiro","mago"],
    name: "Escudo Arcano",
    level: 1,
    school: "Abjuração",
    castingTime: "reaction",
    range: "Pessoal",
    components: "V, S",
    duration: "1 rodada",
    isConcentration: false,
    isRitual: false,
    description: "Uma barreira invisível de força mágica aparece e protege você. Até o início do seu próximo turno, você tem um bônus de +5 na sua CA.",
    effect: "buff",
    targetType: "self",
    reactionTrigger: "when_hit",
    tempAcBonus: 5
  },
  {
    id: "magic_missile",
    classes: ["feiticeiro","mago"],
    name: "Mísseis Mágicos",
    level: 1,
    school: "Evocação",
    castingTime: "action",
    range: "36 metros",
    components: "V, S",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Você cria três dardos brilhantes de força mágica. Cada dardo atinge uma criatura à sua escolha que você possa ver dentro do alcance, causando 1d4 + 1 de dano de força por dardo.",
    damageDice: "1d4+1",
    damageType: "forca",
    spellAttack: false,
    effect: "damage",
    targetType: "multiple"
  },
  {
    id: "cure_wounds",
    classes: ["bardo","clerigo","druida","paladino","guardinha"],
    name: "Curar Ferimentos",
    level: 1,
    school: "Evocação",
    castingTime: "action",
    range: "Toque",
    components: "V, S",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Uma criatura que você tocar recupera uma quantidade de pontos de vida igual a 1d8 + seu modificador de habilidade de conjuração.",
    damageDice: "1d8",
    effect: "heal",
    targetType: "single"
  },
  {
    id: "bless",
    classes: ["clerigo","paladino"],
    name: "Bênção",
    level: 1,
    school: "Encantamento",
    castingTime: "action",
    range: "9 metros",
    components: "V, S, M",
    duration: "1 minuto",
    isConcentration: true,
    isRitual: false,
    description: "Você abençoa até três criaturas. Sempre que um alvo fizer uma jogada de ataque ou teste de resistência antes da magia acabar, ele pode rolar um d4 e adicionar o número rolado ao resultado.",
    effect: "buff",
    targetType: "multiple",
    conditionApplied: "Abençoado"
  },
  {
    id: "detect_magic",
    classes: ["bardo","clerigo","druida","paladino","guardinha","feiticeiro","bruxo","mago"],
    name: "Detectar Magia",
    level: 1,
    school: "Adivinhação",
    castingTime: "action",
    range: "Pessoal",
    components: "V, S",
    duration: "10 minutos",
    isConcentration: true,
    isRitual: true,
    description: "Durante a duração, você sente a presença de magia a até 9 metros de você.",
    effect: "utility",
    targetType: "self"
  },
  {
    id: "feather_fall",
    classes: ["bardo","feiticeiro","mago"],
    name: "Queda Suave",
    level: 1,
    school: "Transmutação",
    castingTime: "reaction",
    range: "18 metros",
    components: "V, M",
    duration: "1 minuto",
    isConcentration: false,
    isRitual: false,
    description: "A taxa de queda de até cinco criaturas caindo que você possa ver a até 18 metros é reduzida para 18m por rodada e elas não tomam dano de queda.",
    effect: "buff",
    targetType: "multiple",
    reactionTrigger: "when_falling"
  },
  {
    id: "thunderwave",
    classes: ["bardo","druida","feiticeiro","mago"],
    name: "Onda Trovejante",
    level: 1,
    school: "Evocação",
    castingTime: "action",
    range: "Pessoal (Cubo 4,5m)",
    components: "V, S",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Uma onda de força trovejante varre a área a partir de você. Teste de CON ou toma 2d8 trovejante e é empurrado 3m.",
    damageDice: "2d8",
    damageType: "trovejante",
    savingThrow: "con",
    effect: "damage",
    targetType: "area"
  },
  {
    id: "sleep",
    classes: ["bardo","feiticeiro","mago"],
    name: "Sono",
    level: 1,
    school: "Encantamento",
    castingTime: "action",
    range: "27 metros",
    components: "V, S, M",
    duration: "1 minuto",
    isConcentration: false,
    isRitual: false,
    description: "A magia envia criaturas para um sono mágico. Role 5d8; o total é o número de PVs de criaturas que essa magia pode afetar.",
    effect: "utility",
    targetType: "area"
  },
  {
    id: "bane",
    classes: ["bardo","clerigo"],
    name: "Perdição",
    level: 1,
    school: "Encantamento",
    castingTime: "action",
    range: "9 metros",
    components: "V, S, M",
    duration: "1 minuto",
    isConcentration: true,
    isRitual: false,
    description: "Até três criaturas devem passar num teste de CAR. Se falharem, sempre que fizerem um teste de ataque ou salvaguarda, subtraem 1d4.",
    effect: "condition",
    targetType: "multiple",
    savingThrow: "car"
  },
  {
    id: "faerie_fire",
    classes: ["bardo","druida"],
    name: "Fogo das Fadas",
    level: 1,
    school: "Evocação",
    castingTime: "action",
    range: "18 metros",
    components: "V",
    duration: "1 minuto",
    isConcentration: true,
    isRitual: false,
    description: "Cada objeto num cubo de 6m é delineado por luz. Criaturas que falhem no teste de DES também. Ataques contra essas criaturas têm vantagem.",
    effect: "condition",
    targetType: "area",
    savingThrow: "des"
  },
  
  // NÍVEL 2
  {
    id: "misty_step",
    classes: ["feiticeiro","mago","bruxo"],
    name: "Passo Nebuloso",
    level: 2,
    school: "Conjuração",
    castingTime: "bonus",
    range: "Pessoal",
    components: "V",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Você é envolto por uma névoa prateada e se teletransporta a até 9 metros para um espaço desocupado que possa ver.",
    effect: "utility",
    targetType: "self"
  },
  {
    id: "shatter",
    classes: ["bardo","feiticeiro","mago","bruxo"],
    name: "Despedaçar",
    level: 2,
    school: "Evocação",
    castingTime: "action",
    range: "18 metros",
    components: "V, S, M",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Um som ensurdecedor irrompe em um ponto à sua escolha. Cada criatura numa esfera de 3m de raio deve fazer um Teste de Resistência de Constituição, sofrendo 3d8 dano trovejante ou metade se passar.",
    damageDice: "3d8",
    damageType: "trovejante",
    savingThrow: "con",
    effect: "damage",
    targetType: "area"
  },
  {
    id: "spiritual_weapon",
    classes: ["clerigo"],
    name: "Arma Espiritual",
    level: 2,
    school: "Evocação",
    castingTime: "bonus",
    range: "18 metros",
    components: "V, S",
    duration: "1 minuto",
    isConcentration: false,
    isRitual: false,
    description: "Você cria uma arma flutuante espectral que ataca com seu bônus de ataque mágico e causa 1d8 + seu modificador de habilidade de força.",
    damageDice: "1d8",
    damageType: "energia",
    spellAttack: true,
    effect: "damage",
    targetType: "single"
  },
  {
    id: "blindness_deafness",
    classes: ["bardo","clerigo","feiticeiro","mago"],
    name: "Cegueira/Surdez",
    level: 2,
    school: "Necromancia",
    castingTime: "action",
    range: "9 metros",
    components: "V",
    duration: "1 minuto",
    isConcentration: false,
    isRitual: false,
    description: "Você pode cegar ou ensurdecer um oponente. Teste de CON para evitar a condição. Cego ou Surdo.",
    effect: "condition",
    targetType: "single",
    savingThrow: "con"
  },
  {
    id: "darkness",
    classes: ["feiticeiro","mago","bruxo"],
    name: "Escuridão",
    level: 2,
    school: "Evocação",
    castingTime: "action",
    range: "18 metros",
    components: "V, M",
    duration: "10 minutos",
    isConcentration: true,
    isRitual: false,
    description: "Escuridão mágica se espalha em uma esfera de 4,5m. Criaturas com visão no escuro não enxergam nela.",
    effect: "utility",
    targetType: "area"
  },
  {
    id: "hold_person",
    classes: ["bardo","clerigo","druida","feiticeiro","mago","bruxo"],
    name: "Imobilizar Pessoa",
    level: 2,
    school: "Encantamento",
    castingTime: "action",
    range: "18 metros",
    components: "V, S, M",
    duration: "1 minuto",
    isConcentration: true,
    isRitual: false,
    description: "Escolha um humanoide. Teste de SAB; se falhar, o alvo fica Paralisado até a magia terminar.",
    effect: "condition",
    targetType: "single",
    savingThrow: "sab"
  },
  {
    id: "invisibility",
    classes: ["bardo","feiticeiro","mago","bruxo"],
    name: "Invisibilidade",
    level: 2,
    school: "Ilusão",
    castingTime: "action",
    range: "Toque",
    components: "V, S, M",
    duration: "1 hora",
    isConcentration: true,
    isRitual: false,
    description: "Uma criatura que você toque se torna invisível até a magia terminar. A magia acaba se o alvo atacar ou conjurar magias.",
    effect: "buff",
    targetType: "single"
  },
  {
    id: "mirror_image",
    classes: ["feiticeiro","mago","bruxo"],
    name: "Reflexos",
    level: 2,
    school: "Ilusão",
    castingTime: "action",
    range: "Pessoal",
    components: "V, S",
    duration: "1 minuto",
    isConcentration: false,
    isRitual: false,
    description: "Três duplicatas ilusórias aparecem. Quando você é atacado, role 1d20 para ver se o ataque acerta você ou um reflexo.",
    effect: "buff",
    targetType: "self"
  },
  {
    id: "web",
    classes: ["feiticeiro","mago"],
    name: "Teia",
    level: 2,
    school: "Conjuração",
    castingTime: "action",
    range: "18 metros",
    components: "V, S, M",
    duration: "1 hora",
    isConcentration: true,
    isRitual: false,
    description: "Teias pegajosas num cubo de 6m. Criaturas na área devem passar num teste de DES ou ficam Restringidas.",
    effect: "condition",
    targetType: "area",
    savingThrow: "des"
  },
  
  // NÍVEL 3
  {
    id: "mass_healing_word",
    classes: ["clerigo"],
    name: "Palavra Curativa em Massa",
    level: 3,
    school: "Evocação",
    castingTime: "bonus",
    range: "18 metros",
    components: "V",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Até seis criaturas à sua escolha que você possa ver dentro do alcance recuperam 1d4 + seu modificador de conjuração pontos de vida.",
    damageDice: "1d4",
    effect: "heal",
    targetType: "multiple"
  },
  {
    id: "spirit_guardians",
    classes: ["clerigo"],
    name: "Espíritos Guardiões",
    level: 3,
    school: "Conjuração",
    castingTime: "action",
    range: "Pessoal (4,5m de raio)",
    components: "V, S, M",
    duration: "10 minutos",
    isConcentration: true,
    isRitual: false,
    description: "Espíritos flutuam ao seu redor num raio de 4,5m. Inimigos que começam o turno na área sofrem 3d8 de dano radiante/necrótico (Teste Sab reduz à metade) e o deslocamento deles cai pela metade.",
    damageDice: "3d8",
    damageType: "radiante",
    savingThrow: "sab",
    effect: "damage",
    targetType: "area"
  },
  {
    id: "counterspell",
    classes: ["feiticeiro","mago","bruxo"],
    name: "Contramágica",
    level: 3,
    school: "Abjuração",
    castingTime: "reaction",
    range: "18 metros",
    components: "S",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Você interrompe uma criatura no processo de conjuração. Magias de nível 3 ou inferior falham. Para magias de nível superior, faça um teste do seu atributo de conjuração (CD = 10 + nível da magia).",
    effect: "utility",
    targetType: "single",
    reactionTrigger: "spell_cast"
  },
  {
    id: "dispel_magic",
    classes: ["bardo","clerigo","druida","paladino","feiticeiro","mago","bruxo"],
    name: "Dissipar Magia",
    level: 3,
    school: "Abjuração",
    castingTime: "action",
    range: "36 metros",
    components: "V, S",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Escolha uma criatura, objeto ou efeito mágico. Qualquer magia de nível 3 ou inferior no alvo é encerrada. Para magias superiores, faça um teste do seu atributo (CD = 10 + nível da magia).",
    effect: "utility",
    targetType: "single"
  },
  {
    id: "fly",
    classes: ["feiticeiro","mago","bruxo"],
    name: "Voar",
    level: 3,
    school: "Transmutação",
    castingTime: "action",
    range: "Toque",
    components: "V, S, M",
    duration: "10 minutos",
    isConcentration: true,
    isRitual: false,
    description: "Você toca uma criatura. Ela ganha deslocamento de voo de 18m pelo tempo da duração.",
    effect: "buff",
    targetType: "single"
  },
  {
    id: "haste",
    classes: ["feiticeiro","mago"],
    name: "Velocidade",
    level: 3,
    school: "Transmutação",
    castingTime: "action",
    range: "9 metros",
    components: "V, S, M",
    duration: "1 minuto",
    isConcentration: true,
    isRitual: false,
    description: "O alvo ganha +2 de CA, vantagem em salvaguardas de DES, o dobro do deslocamento e uma ação extra por turno (apenas para Atacar 1 vez, Disparar, Desengajar, Esconder ou Usar Objeto).",
    effect: "buff",
    targetType: "single"
  },
  {
    id: "slow",
    classes: ["bardo","feiticeiro","mago"],
    name: "Lentidão",
    level: 3,
    school: "Transmutação",
    castingTime: "action",
    range: "36 metros",
    components: "V, S, M",
    duration: "1 minuto",
    isConcentration: true,
    isRitual: false,
    description: "Altera o tempo num cubo de 12m. Teste de SAB. Na falha, sofre -2 de CA, -2 DES, deslocamento cai pela metade e não pode ter reações ou múltiplos ataques.",
    effect: "condition",
    targetType: "area",
    savingThrow: "sab"
  },
  {
    id: "revivify",
    classes: ["clerigo","paladino"],
    name: "Reviver",
    level: 3,
    school: "Necromancia",
    castingTime: "action",
    range: "Toque",
    components: "V, S, M",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Você toca uma criatura que tenha morrido no último minuto. A criatura volta à vida com 1 ponto de vida.",
    effect: "heal",
    targetType: "single"
  },
  {
    id: "hypnotic_pattern",
    classes: ["bardo","feiticeiro","mago","bruxo"],
    name: "Padrão Hipnótico",
    level: 3,
    school: "Ilusão",
    castingTime: "action",
    range: "36 metros",
    components: "S, M",
    duration: "1 minuto",
    isConcentration: true,
    isRitual: false,
    description: "Cores num cubo de 9m. Teste de SAB. Na falha, a criatura fica Enfeitiçada, Incapacitada e com deslocamento 0 enquanto você concentrar.",
    effect: "condition",
    targetType: "area",
    savingThrow: "sab"
  },
  {
    id: "fear",
    classes: ["bardo","feiticeiro","mago","bruxo"],
    name: "Medo",
    level: 3,
    school: "Ilusão",
    castingTime: "action",
    range: "Pessoal (Cone 9m)",
    components: "V, S, M",
    duration: "1 minuto",
    isConcentration: true,
    isRitual: false,
    description: "Projeta uma imagem apavorante num cone de 9m. Teste de SAB ou fica Amedrontada e deve largar o que segura e fugir de você.",
    effect: "condition",
    targetType: "area",
    savingThrow: "sab"
  },
  {
    id: "fireball",
    classes: ["feiticeiro","mago"],
    name: "Bola de Fogo",
    level: 3,
    school: "Evocação",
    castingTime: "action",
    range: "45 metros",
    components: "V, S, M",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Uma explosão de fogo em uma esfera de 6m de raio. Cada criatura deve fazer um Teste de Resistência de Destreza. Uma criatura sofre 8d6 de dano de fogo em uma falha, ou metade se passar.",
    damageDice: "8d6",
    damageType: "fogo",
    savingThrow: "des",
    effect: "damage",
    targetType: "area"
  },
  
  // NÍVEL 4
  {
    id: "polymorph",
    classes: ["bardo","druida","feiticeiro","mago"],
    name: "Polimorfo",
    level: 4,
    school: "Transmutação",
    castingTime: "action",
    range: "18 metros",
    components: "V, S, M",
    duration: "1 hora",
    isConcentration: true,
    isRitual: false,
    description: "Transforma uma criatura que você possa ver dentro do alcance em uma nova forma. Um alvo involuntário deve ser bem sucedido em um teste de SAB.",
    savingThrow: "sab",
    effect: "utility",
    targetType: "single"
  },

  // NÍVEL 5
  {
    id: "cone_of_cold",
    classes: ["feiticeiro","mago"],
    name: "Cone de Frio",
    level: 5,
    school: "Evocação",
    castingTime: "action",
    range: "Pessoal (Cone 18m)",
    components: "V, S, M",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Uma explosão de ar frio entra em erupção de suas mãos. Cada criatura em um cone de 18 metros deve fazer um Teste de Resistência de CON, sofrendo 8d8 dano de frio na falha.",
    damageDice: "8d8",
    damageType: "frio",
    savingThrow: "con",
    effect: "damage",
    targetType: "area"
  },
  
  // NOVAS MAGIAS (Feiticeiro da Tempestade e Afins)
  // TRUQUES
  {
    id: "shocking_grasp",
    classes: ["feiticeiro","mago"],
    name: "Toque Chocante",
    level: 0,
    school: "Evocação",
    castingTime: "action",
    range: "Toque",
    components: "V, S",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Energia elétrica surge na sua mão. Faça um ataque corpo a corpo com magia. Você tem vantagem se o alvo estiver usando armadura de metal. Num acerto, sofre 1d8 dano elétrico e não pode ter reações até o início do próximo turno.",
    damageDice: "1d8",
    damageType: "eletrico",
    spellAttack: true,
    effect: "damage",
    targetType: "single"
  },
  {
    id: "thunderclap",
    classes: ["bardo","druida","feiticeiro","mago","bruxo"],
    name: "Trovoada",
    level: 0,
    school: "Evocação",
    castingTime: "action",
    range: "Pessoal (1,5m)",
    components: "S",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Você cria uma explosão de som trovejante que pode ser ouvida a 30m. Cada criatura a até 1,5m deve passar num teste de Constituição ou sofre 1d6 dano trovejante.",
    damageDice: "1d6",
    damageType: "trovejante",
    savingThrow: "con",
    effect: "damage",
    targetType: "area"
  },
  {
    id: "lightning_lure",
    classes: ["feiticeiro","mago","bruxo"],
    name: "Atração Relampejante",
    level: 0,
    school: "Evocação",
    castingTime: "action",
    range: "4,5 metros",
    components: "V",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Um chicote de energia elétrica atinge uma criatura que você possa ver a até 4,5m. Teste de Força, se falhar é puxada 3m na sua direção e sofre 1d8 dano elétrico se terminar a até 1,5m de você.",
    damageDice: "1d8",
    damageType: "eletrico",
    savingThrow: "for",
    effect: "damage",
    targetType: "single"
  },
  
  // NÍVEL 1
  {
    id: "witch_bolt",
    classes: ["feiticeiro","mago","bruxo"],
    name: "Raio de Bruxa",
    level: 1,
    school: "Evocação",
    castingTime: "action",
    range: "9 metros",
    components: "V, S, M",
    duration: "1 minuto",
    isConcentration: true,
    isRitual: false,
    description: "Um raio azul vai de você até um alvo. Faça um ataque com magia à distância. Num acerto, sofre 1d12 de dano elétrico. Nos turnos seguintes, você pode usar sua ação para causar 1d12 dano elétrico automaticamente enquanto a magia durar.",
    damageDice: "1d12",
    damageType: "eletrico",
    spellAttack: true,
    effect: "damage",
    targetType: "single"
  },
  {
    id: "thunderous_smite",
    classes: ["paladino"],
    name: "Destruição Trovejante",
    level: 1,
    school: "Evocação",
    castingTime: "bonus",
    range: "Pessoal",
    components: "V",
    duration: "1 minuto",
    isConcentration: true,
    isRitual: false,
    description: "A primeira vez que você acertar um ataque corpo a corpo durante a magia, a arma ressoa com trovão visível, causando 2d6 dano trovejante extra. Alvo faz teste de FOR ou é empurrado 3m e cai Prone.",
    damageDice: "2d6",
    damageType: "trovejante",
    savingThrow: "for",
    effect: "damage",
    targetType: "self"
  },

  // NÍVEL 3
  {
    id: "lightning_bolt",
    classes: ["feiticeiro","mago"],
    name: "Relâmpago",
    level: 3,
    school: "Evocação",
    castingTime: "action",
    range: "Pessoal (Linha 30m)",
    components: "V, S, M",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Um traço de relâmpago forma uma linha com 30 metros de comprimento e 1,5 metro de largura na direção que você escolher. Cada criatura deve fazer um teste de Destreza, sofrendo 8d6 de dano elétrico se falhar (metade no sucesso).",
    damageDice: "8d6",
    damageType: "eletrico",
    savingThrow: "des",
    effect: "damage",
    targetType: "area"
  },
  {
    id: "call_lightning",
    classes: ["druida"],
    name: "Convocar Relâmpagos",
    level: 3,
    school: "Conjuração",
    castingTime: "action",
    range: "36 metros",
    components: "V, S",
    duration: "10 minutos",
    isConcentration: true,
    isRitual: false,
    description: "Uma nuvem de tempestade aparece a 36m do chão. Você escolhe um ponto e um relâmpago cai dele. Teste de Destreza, sofrendo 3d10 dano elétrico. Você pode repetir a ação em seus turnos seguintes para conjurar novos relâmpagos.",
    damageDice: "3d10",
    damageType: "eletrico",
    savingThrow: "des",
    effect: "damage",
    targetType: "area"
  },

  // NÍVEL 4
  {
    id: "storm_sphere",
    classes: ["feiticeiro","mago"],
    name: "Esfera da Tempestade",
    level: 4,
    school: "Evocação",
    castingTime: "action",
    range: "45 metros",
    components: "V, S",
    duration: "1 minuto",
    isConcentration: true,
    isRitual: false,
    description: "Uma esfera de ventos uivantes de 6m cria área de terreno difícil. Criaturas lá dentro sofrem desvantagem em ouvir. Ficar lá força um teste de Força sofrendo 2d6 concussão. Com ação bônus, você lança um raio da esfera num alvo a 18m dela, ataque com magia causa 4d6 dano elétrico.",
    damageDice: "4d6",
    damageType: "eletrico",
    spellAttack: true,
    effect: "damage",
    targetType: "area"
  },

  // NÍVEL 6
  {
    id: "chain_lightning",
    classes: ["feiticeiro","mago"],
    name: "Corrente de Relâmpagos",
    level: 6,
    school: "Evocação",
    castingTime: "action",
    range: "45 metros",
    components: "V, S, M",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Você cria um relâmpago que acerta um alvo à escolha. Em seguida, três raios secundários saltam desse alvo para até 3 outras criaturas num raio de 9m do alvo inicial. Todos fazem teste de Destreza, sofrendo 10d8 dano elétrico (metade se passar).",
    damageDice: "10d8",
    damageType: "eletrico",
    savingThrow: "des",
    effect: "damage",
    targetType: "multiple"
  },
  // ============================================
  // MAGIAS ADICIONAIS: FEITICEIRO E PALADINO
  // Automatizadas com efeitos de dano, buff e condição
  // ============================================

  // --- TRUQUES ---
  {
    id: "acid_splash",
    name: "Espirro Ácido",
    level: 0,
    school: "Conjuração",
    castingTime: "action",
    range: "18 metros",
    components: "V, S",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Você arremessa uma bolha de ácido. Escolha uma ou duas criaturas a até 1,5m uma da outra. Teste de Destreza ou sofrem 1d6 dano de ácido.",
    damageDice: "1d6",
    damageType: "acido",
    savingThrow: "des",
    effect: "damage",
    targetType: "multiple",
    classes: ["feiticeiro", "mago"]
  },
  {
    id: "chill_touch",
    name: "Toque Arrepiante",
    level: 0,
    school: "Necromancia",
    castingTime: "action",
    range: "36 metros",
    components: "V, S",
    duration: "1 rodada",
    isConcentration: false,
    isRitual: false,
    description: "Uma mão cadavérica ataca o alvo. Ataque mágico. Em acerto, sofre 1d8 dano necrótico e não pode recuperar PV até o início do seu próximo turno.",
    damageDice: "1d8",
    damageType: "necrotico",
    spellAttack: true,
    effect: "damage",
    targetType: "single",
    conditionApplied: "Toque Arrepiante",
    classes: ["bruxo", "feiticeiro", "mago"]
  },
  {
    id: "poison_spray",
    name: "Rajada de Veneno",
    level: 0,
    school: "Conjuração",
    castingTime: "action",
    range: "3 metros",
    components: "V, S",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Você projeta um gás tóxico. Teste de Constituição ou sofre 1d12 de dano de veneno.",
    damageDice: "1d12",
    damageType: "veneno",
    savingThrow: "con",
    effect: "damage",
    targetType: "single",
    classes: ["druida", "feiticeiro", "bruxo", "mago"]
  },

  // --- NÍVEL 1 ---
  {
    id: "burning_hands",
    name: "Mãos Flamejantes",
    level: 1,
    school: "Evocação",
    castingTime: "action",
    range: "Cone de 4,5m",
    components: "V, S",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Labaredas disparam de seus dedos num cone. Teste de Destreza ou 3d6 dano de fogo (metade no sucesso).",
    damageDice: "3d6",
    damageType: "fogo",
    savingThrow: "des",
    effect: "damage",
    targetType: "area",
    classes: ["feiticeiro", "mago"]
  },
  {
    id: "chromatic_orb",
    name: "Orbe Cromático",
    level: 1,
    school: "Evocação",
    castingTime: "action",
    range: "27 metros",
    components: "V, S, M",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Ataque mágico. Se acertar, causa 3d8 de dano (ácido, frio, fogo, elétrico, venenoso ou trovejante).",
    damageDice: "3d8",
    damageType: "energia", // Player chooses element
    spellAttack: true,
    effect: "damage",
    targetType: "single",
    classes: ["feiticeiro", "mago"]
  },
  {
    id: "command",
    name: "Comando",
    level: 1,
    school: "Encantamento",
    castingTime: "action",
    range: "18 metros",
    components: "V",
    duration: "1 rodada",
    isConcentration: false,
    isRitual: false,
    description: "Você fala uma palavra de comando. Teste de Sabedoria ou alvo segue o comando (fugir, largar, deitar, parar) no próximo turno.",
    effect: "condition",
    targetType: "single",
    savingThrow: "sab",
    conditionApplied: "Comandado",
    classes: ["clerigo", "paladino"]
  },
  {
    id: "divine_favor",
    name: "Favor Divino",
    level: 1,
    school: "Evocação",
    castingTime: "bonus",
    range: "Pessoal",
    components: "V, S",
    duration: "1 minuto",
    isConcentration: true,
    isRitual: false,
    description: "Sua arma fica imbuída com poder divino, causando 1d4 de dano radiante extra ao acertar um ataque.",
    effect: "buff",
    targetType: "self",
    conditionApplied: "Favor Divino",
    classes: ["paladino"]
  },
  {
    id: "searing_smite",
    name: "Destruição Ardente",
    level: 1,
    school: "Evocação",
    castingTime: "bonus",
    range: "Pessoal",
    components: "V",
    duration: "1 minuto",
    isConcentration: true,
    isRitual: false,
    description: "Seu próximo acerto com arma causa +1d6 dano de fogo e alvo pega fogo. Teste CON ou 1d6 fogo a cada turno.",
    damageDice: "1d6",
    damageType: "fogo",
    effect: "buff",
    targetType: "self",
    conditionApplied: "Destruição Ardente",
    classes: ["paladino"]
  },
  {
    id: "wrathful_smite",
    name: "Destruição Colérica",
    level: 1,
    school: "Evocação",
    castingTime: "bonus",
    range: "Pessoal",
    components: "V",
    duration: "1 minuto",
    isConcentration: true,
    isRitual: false,
    description: "Próximo acerto causa +1d6 dano psíquico. Teste de Sabedoria ou alvo fica Amedrontado até a magia acabar.",
    damageDice: "1d6",
    damageType: "psiquico",
    effect: "buff",
    targetType: "self",
    conditionApplied: "Destruição Colérica",
    classes: ["paladino"]
  },
  {
    id: "false_life",
    name: "Vida Falsa",
    level: 1,
    school: "Necromancia",
    castingTime: "action",
    range: "Pessoal",
    components: "V, S, M",
    duration: "1 hora",
    isConcentration: false,
    isRitual: false,
    description: "Você ganha 1d4+4 Pontos de Vida Temporários por 1 hora.",
    effect: "buff",
    targetType: "self",
    conditionApplied: "Vida Falsa",
    classes: ["feiticeiro", "mago", "bruxo"]
  },
  {
    id: "heroism",
    name: "Heroísmo",
    level: 1,
    school: "Encantamento",
    castingTime: "action",
    range: "Toque",
    components: "V, S",
    duration: "1 minuto",
    isConcentration: true,
    isRitual: false,
    description: "Alvo se torna imune a Amedrontado e ganha PV temporários igual seu mod de conjuração todo turno.",
    effect: "buff",
    targetType: "single",
    conditionApplied: "Heroísmo",
    classes: ["bardo", "paladino"]
  },

  // --- NÍVEL 2 ---
  {
    id: "scorching_ray",
    name: "Raio Ardente",
    level: 2,
    school: "Evocação",
    castingTime: "action",
    range: "36 metros",
    components: "V, S",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Você cria 3 raios de fogo e dispara. Cada raio requer ataque com magia. Em acerto, cada raio causa 2d6 dano de fogo.",
    damageDice: "2d6",
    damageType: "fogo",
    spellAttack: true,
    effect: "damage",
    targetType: "multiple",
    classes: ["feiticeiro", "mago"]
  },
  {
    id: "blur",
    name: "Borrão",
    level: 2,
    school: "Ilusão",
    castingTime: "action",
    range: "Pessoal",
    components: "V",
    duration: "1 minuto",
    isConcentration: true,
    isRitual: false,
    description: "Seu corpo se distorce ilusoriamente. Ataques contra você têm desvantagem.",
    effect: "buff",
    targetType: "self",
    conditionApplied: "Borrão",
    classes: ["feiticeiro", "mago"]
  },
  {
    id: "enlarge_reduce",
    name: "Aumentar/Reduzir",
    level: 2,
    school: "Transmutação",
    castingTime: "action",
    range: "9 metros",
    components: "V, S, M",
    duration: "1 minuto",
    isConcentration: true,
    isRitual: false,
    description: "Aumenta o alvo (Vantagem FOR e +1d4 de dano corpo a corpo) ou Reduz o alvo (Desvantagem FOR e -1d4 dano).",
    effect: "buff",
    targetType: "single",
    conditionApplied: "Alterado (Tamanho)",
    classes: ["bardo", "feiticeiro", "mago"]
  },
  {
    id: "aid",
    name: "Ajuda",
    level: 2,
    school: "Abjuração",
    castingTime: "action",
    range: "9 metros",
    components: "V, S, M",
    duration: "8 horas",
    isConcentration: false,
    isRitual: false,
    description: "Até 3 criaturas aumentam seus PV máximos e atuais em 5.",
    effect: "buff",
    targetType: "multiple",
    conditionApplied: "Ajuda",
    classes: ["clerigo", "paladino"]
  },
  {
    id: "branding_smite",
    name: "Destruição Marcante",
    level: 2,
    school: "Evocação",
    castingTime: "bonus",
    range: "Pessoal",
    components: "V",
    duration: "1 minuto",
    isConcentration: true,
    isRitual: false,
    description: "Próximo acerto causa +2d6 dano radiante. O alvo brilha e não pode ficar invisível.",
    damageDice: "2d6",
    damageType: "radiante",
    effect: "buff",
    targetType: "self",
    conditionApplied: "Destruição Marcante",
    classes: ["paladino"]
  },
  {
    id: "magic_weapon",
    name: "Arma Mágica",
    level: 2,
    school: "Transmutação",
    castingTime: "bonus",
    range: "Toque",
    components: "V, S",
    duration: "1 hora",
    isConcentration: true,
    isRitual: false,
    description: "Uma arma não mágica ganha bônus de +1 nas rolagens de ataque e dano.",
    effect: "buff",
    targetType: "single",
    conditionApplied: "Arma Mágica (+1)",
    classes: ["paladino", "mago", "feiticeiro"]
  },
  {
    id: "lesser_restoration",
    name: "Restauração Menor",
    level: 2,
    school: "Abjuração",
    castingTime: "action",
    range: "Toque",
    components: "V, S",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Toca uma criatura para remover uma condição: Cego, Surdo, Paralisado ou Envenenado.",
    effect: "heal",
    targetType: "single",
    classes: ["bardo", "clerigo", "druida", "paladino", "guardinha"]
  }

];
