import { SpellEntry } from '../gameData';

export const SPELLS_DB: SpellEntry[] = [
  // NÍVEL 0 (TRUQUES)
  {
    id: "fire_bolt",
    name: "Raio de Fogo",
    level: 0,
    school: "Evocação",
    castingTime: "action",
    range: "36 metros",
    components: "V, S",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Você arremessa um cisco de fogo em uma criatura ou objeto. Faça um ataque à distância com magia. Em um acerto, o alvo sofre 1d10 de dano de fogo.",
    damageDice: "1d10",
    damageType: "fogo",
    spellAttack: true,
    effect: "damage",
    targetType: "single"
  },
  {
    id: "light",
    name: "Luz",
    level: 0,
    school: "Evocação",
    castingTime: "action",
    range: "Toque",
    components: "V, M",
    duration: "1 hora",
    isConcentration: false,
    isRitual: false,
    description: "Você toca um objeto que não tenha mais de 3 metros. Até o fim da magia, o objeto emite luz plena num raio de 6 metros e penumbra por mais 6 metros.",
    effect: "utility",
    targetType: "single"
  },
  {
    id: "guidance",
    name: "Orientação",
    level: 0,
    school: "Adivinhação",
    castingTime: "action",
    range: "Toque",
    components: "V, S",
    duration: "1 minuto",
    isConcentration: true,
    isRitual: false,
    description: "Você toca uma criatura voluntária. Uma vez antes da magia acabar, o alvo pode rolar 1d4 e adicionar o número rolado a um teste de habilidade de sua escolha.",
    effect: "buff",
    targetType: "single"
  },
  {
    id: "mage_hand",
    name: "Mãos Mágicas",
    level: 0,
    school: "Conjuração",
    castingTime: "action",
    range: "9 metros",
    components: "V, S",
    duration: "1 minuto",
    isConcentration: false,
    isRitual: false,
    description: "Uma mão espectral flutuante aparece num ponto. Você pode usar a mão para manipular objetos, abrir portas, etc.",
    effect: "utility",
    targetType: "single"
  },
  {
    id: "minor_illusion",
    name: "Ilusão Menor",
    level: 0,
    school: "Ilusão",
    castingTime: "action",
    range: "9 metros",
    components: "S, M",
    duration: "1 minuto",
    isConcentration: false,
    isRitual: false,
    description: "Você cria um som ou imagem de um objeto dentro do alcance. A ilusão tem a duração de 1 minuto.",
    effect: "utility",
    targetType: "single"
  },
  {
    id: "eldritch_blast",
    name: "Rajada Mística",
    level: 0,
    school: "Evocação",
    castingTime: "action",
    range: "36 metros",
    components: "V, S",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Um feixe de energia crepitante vai em direção a uma criatura. Em um acerto, o alvo sofre 1d10 de dano de força.",
    damageDice: "1d10",
    damageType: "forca",
    spellAttack: true,
    effect: "damage",
    targetType: "single"
  },
  {
    id: "sacred_flame",
    name: "Chama Sagrada",
    level: 0,
    school: "Evocação",
    castingTime: "action",
    range: "18 metros",
    components: "V, S",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Chamas divinas descem sobre uma criatura que você possa ver. O alvo deve passar num teste de Destreza ou sofrerá 1d8 de dano radiante.",
    damageDice: "1d8",
    damageType: "radiante",
    savingThrow: "des",
    effect: "damage",
    targetType: "single"
  },
  {
    id: "ray_of_frost",
    name: "Raio de Gelo",
    level: 0,
    school: "Evocação",
    castingTime: "action",
    range: "18 metros",
    components: "V, S",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Um raio de luz azulada vai em direção à criatura. Em um acerto, sofre 1d8 dano de frio e o deslocamento dela é reduzido em 3m até o próximo turno.",
    damageDice: "1d8",
    damageType: "frio",
    spellAttack: true,
    effect: "damage",
    targetType: "single"
  },
  
  // NÍVEL 1
  {
    id: "mage_armor",
    name: "Armadura Arcana",
    level: 1,
    school: "Abjuração",
    castingTime: "action",
    range: "Toque",
    components: "V, S, M",
    duration: "8 horas",
    isConcentration: false,
    isRitual: false,
    description: "Você toca uma criatura voluntária que não esteja usando armadura. Até a magia acabar, a CA base do alvo se torna 13 + seu modificador de Destreza.",
    effect: "buff",
    targetType: "single"
  },
  {
    id: "shield_of_faith",
    name: "Escudo da Fé",
    level: 1,
    school: "Abjuração",
    castingTime: "bonus",
    range: "18 metros",
    components: "V, S, M",
    duration: "10 minutos",
    isConcentration: true,
    isRitual: false,
    description: "Um campo cintilante aparece ao redor de uma criatura da sua escolha dentro do alcance, concedendo um bônus de +2 na CA durante a duração.",
    effect: "buff",
    targetType: "single"
  },
  {
    id: "healing_word",
    name: "Palavra Curativa",
    level: 1,
    school: "Evocação",
    castingTime: "bonus",
    range: "18 metros",
    components: "V",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Uma criatura à sua escolha que você possa ver, recupera 1d4 + seu modificador de habilidade de conjuração pontos de vida.",
    damageDice: "1d4",
    effect: "heal",
    targetType: "single"
  },
  {
    id: "shield",
    name: "Escudo Arcano",
    level: 1,
    school: "Abjuração",
    castingTime: "reaction",
    range: "Pessoal",
    components: "V, S",
    duration: "1 rodada",
    isConcentration: false,
    isRitual: false,
    description: "Uma barreira invisível de força mágica aparece e protege você. Até o início do seu próximo turno, você tem um bônus de +5 na sua CA.",
    effect: "buff",
    targetType: "self",
    reactionTrigger: "when_hit",
    tempAcBonus: 5
  },
  {
    id: "magic_missile",
    name: "Mísseis Mágicos",
    level: 1,
    school: "Evocação",
    castingTime: "action",
    range: "36 metros",
    components: "V, S",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Você cria três dardos brilhantes de força mágica. Cada dardo atinge uma criatura à sua escolha que você possa ver dentro do alcance, causando 1d4 + 1 de dano de força por dardo.",
    damageDice: "1d4+1",
    damageType: "forca",
    spellAttack: false,
    effect: "damage",
    targetType: "multiple"
  },
  {
    id: "cure_wounds",
    name: "Curar Ferimentos",
    level: 1,
    school: "Evocação",
    castingTime: "action",
    range: "Toque",
    components: "V, S",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Uma criatura que você tocar recupera uma quantidade de pontos de vida igual a 1d8 + seu modificador de habilidade de conjuração.",
    damageDice: "1d8",
    effect: "heal",
    targetType: "single"
  },
  {
    id: "bless",
    name: "Bênção",
    level: 1,
    school: "Encantamento",
    castingTime: "action",
    range: "9 metros",
    components: "V, S, M",
    duration: "1 minuto",
    isConcentration: true,
    isRitual: false,
    description: "Você abençoa até três criaturas. Sempre que um alvo fizer uma jogada de ataque ou teste de resistência antes da magia acabar, ele pode rolar um d4 e adicionar o número rolado ao resultado.",
    effect: "buff",
    targetType: "multiple",
    conditionApplied: "Abençoado"
  },
  {
    id: "detect_magic",
    name: "Detectar Magia",
    level: 1,
    school: "Adivinhação",
    castingTime: "action",
    range: "Pessoal",
    components: "V, S",
    duration: "10 minutos",
    isConcentration: true,
    isRitual: true,
    description: "Durante a duração, você sente a presença de magia a até 9 metros de você.",
    effect: "utility",
    targetType: "self"
  },
  {
    id: "feather_fall",
    name: "Queda Suave",
    level: 1,
    school: "Transmutação",
    castingTime: "reaction",
    range: "18 metros",
    components: "V, M",
    duration: "1 minuto",
    isConcentration: false,
    isRitual: false,
    description: "A taxa de queda de até cinco criaturas caindo que você possa ver a até 18 metros é reduzida para 18m por rodada e elas não tomam dano de queda.",
    effect: "buff",
    targetType: "multiple",
    reactionTrigger: "falling"
  },
  {
    id: "thunderwave",
    name: "Onda Trovejante",
    level: 1,
    school: "Evocação",
    castingTime: "action",
    range: "Pessoal (Cubo 4,5m)",
    components: "V, S",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Uma onda de força trovejante varre a área a partir de você. Teste de CON ou toma 2d8 trovejante e é empurrado 3m.",
    damageDice: "2d8",
    damageType: "trovejante",
    savingThrow: "con",
    effect: "damage",
    targetType: "area"
  },
  {
    id: "sleep",
    name: "Sono",
    level: 1,
    school: "Encantamento",
    castingTime: "action",
    range: "27 metros",
    components: "V, S, M",
    duration: "1 minuto",
    isConcentration: false,
    isRitual: false,
    description: "A magia envia criaturas para um sono mágico. Role 5d8; o total é o número de PVs de criaturas que essa magia pode afetar.",
    effect: "utility",
    targetType: "area"
  },
  {
    id: "bane",
    name: "Perdição",
    level: 1,
    school: "Encantamento",
    castingTime: "action",
    range: "9 metros",
    components: "V, S, M",
    duration: "1 minuto",
    isConcentration: true,
    isRitual: false,
    description: "Até três criaturas devem passar num teste de CAR. Se falharem, sempre que rolarem ataque ou salvaguarda, subtraem 1d4.",
    effect: "debuff",
    targetType: "multiple",
    savingThrow: "car"
  },
  {
    id: "faerie_fire",
    name: "Fogo das Fadas",
    level: 1,
    school: "Evocação",
    castingTime: "action",
    range: "18 metros",
    components: "V",
    duration: "1 minuto",
    isConcentration: true,
    isRitual: false,
    description: "Cada objeto num cubo de 6m é delineado por luz. Criaturas que falhem no teste de DES também. Ataques contra essas criaturas têm vantagem.",
    effect: "debuff",
    targetType: "area",
    savingThrow: "des"
  },
  
  // NÍVEL 2
  {
    id: "misty_step",
    name: "Passo Nebuloso",
    level: 2,
    school: "Conjuração",
    castingTime: "bonus",
    range: "Pessoal",
    components: "V",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Você é envolto por uma névoa prateada e se teletransporta a até 9 metros para um espaço desocupado que possa ver.",
    effect: "utility",
    targetType: "self"
  },
  {
    id: "shatter",
    name: "Despedaçar",
    level: 2,
    school: "Evocação",
    castingTime: "action",
    range: "18 metros",
    components: "V, S, M",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Um som ensurdecedor irrompe em um ponto à sua escolha. Cada criatura numa esfera de 3m de raio deve fazer um Teste de Resistência de Constituição, sofrendo 3d8 dano trovejante ou metade se passar.",
    damageDice: "3d8",
    damageType: "trovejante",
    savingThrow: "con",
    effect: "damage",
    targetType: "area"
  },
  {
    id: "spiritual_weapon",
    name: "Arma Espiritual",
    level: 2,
    school: "Evocação",
    castingTime: "bonus",
    range: "18 metros",
    components: "V, S",
    duration: "1 minuto",
    isConcentration: false,
    isRitual: false,
    description: "Você cria uma arma flutuante espectral que ataca com seu bônus de ataque mágico e causa 1d8 + seu modificador de habilidade de força.",
    damageDice: "1d8",
    damageType: "energia",
    spellAttack: true,
    effect: "damage",
    targetType: "single"
  },
  {
    id: "blindness_deafness",
    name: "Cegueira/Surdez",
    level: 2,
    school: "Necromancia",
    castingTime: "action",
    range: "9 metros",
    components: "V",
    duration: "1 minuto",
    isConcentration: false,
    isRitual: false,
    description: "Você pode cegar ou ensurdecer um oponente. Teste de CON para evitar a condição. Cego ou Surdo.",
    effect: "debuff",
    targetType: "single",
    savingThrow: "con"
  },
  {
    id: "darkness",
    name: "Escuridão",
    level: 2,
    school: "Evocação",
    castingTime: "action",
    range: "18 metros",
    components: "V, M",
    duration: "10 minutos",
    isConcentration: true,
    isRitual: false,
    description: "Escuridão mágica se espalha em uma esfera de 4,5m. Criaturas com visão no escuro não enxergam nela.",
    effect: "utility",
    targetType: "area"
  },
  {
    id: "hold_person",
    name: "Imobilizar Pessoa",
    level: 2,
    school: "Encantamento",
    castingTime: "action",
    range: "18 metros",
    components: "V, S, M",
    duration: "1 minuto",
    isConcentration: true,
    isRitual: false,
    description: "Escolha um humanoide. Teste de SAB; se falhar, o alvo fica Paralisado até a magia terminar.",
    effect: "debuff",
    targetType: "single",
    savingThrow: "sab"
  },
  {
    id: "invisibility",
    name: "Invisibilidade",
    level: 2,
    school: "Ilusão",
    castingTime: "action",
    range: "Toque",
    components: "V, S, M",
    duration: "1 hora",
    isConcentration: true,
    isRitual: false,
    description: "Uma criatura que você toque se torna invisível até a magia terminar. A magia acaba se o alvo atacar ou conjurar magias.",
    effect: "buff",
    targetType: "single"
  },
  {
    id: "mirror_image",
    name: "Reflexos",
    level: 2,
    school: "Ilusão",
    castingTime: "action",
    range: "Pessoal",
    components: "V, S",
    duration: "1 minuto",
    isConcentration: false,
    isRitual: false,
    description: "Três duplicatas ilusórias aparecem. Quando você é atacado, role 1d20 para ver se o ataque acerta você ou um reflexo.",
    effect: "buff",
    targetType: "self"
  },
  {
    id: "web",
    name: "Teia",
    level: 2,
    school: "Conjuração",
    castingTime: "action",
    range: "18 metros",
    components: "V, S, M",
    duration: "1 hora",
    isConcentration: true,
    isRitual: false,
    description: "Teias pegajosas num cubo de 6m. Criaturas na área devem passar num teste de DES ou ficam Restringidas.",
    effect: "debuff",
    targetType: "area",
    savingThrow: "des"
  },
  
  // NÍVEL 3
  {
    id: "mass_healing_word",
    name: "Palavra Curativa em Massa",
    level: 3,
    school: "Evocação",
    castingTime: "bonus",
    range: "18 metros",
    components: "V",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Até seis criaturas à sua escolha que você possa ver dentro do alcance recuperam 1d4 + seu modificador de conjuração pontos de vida.",
    damageDice: "1d4",
    effect: "heal",
    targetType: "multiple"
  },
  {
    id: "spirit_guardians",
    name: "Espíritos Guardiões",
    level: 3,
    school: "Conjuração",
    castingTime: "action",
    range: "Pessoal (4,5m de raio)",
    components: "V, S, M",
    duration: "10 minutos",
    isConcentration: true,
    isRitual: false,
    description: "Espíritos flutuam ao seu redor num raio de 4,5m. Inimigos que começam o turno na área sofrem 3d8 de dano radiante/necrótico (Teste Sab reduz à metade) e o deslocamento deles cai pela metade.",
    damageDice: "3d8",
    damageType: "radiante",
    savingThrow: "sab",
    effect: "damage",
    targetType: "area"
  },
  {
    id: "counterspell",
    name: "Contramágica",
    level: 3,
    school: "Abjuração",
    castingTime: "reaction",
    range: "18 metros",
    components: "S",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Você interrompe uma criatura no processo de conjuração. Magias de nível 3 ou inferior falham. Para magias de nível superior, faça um teste do seu atributo de conjuração (CD = 10 + nível da magia).",
    effect: "utility",
    targetType: "single",
    reactionTrigger: "spell_cast"
  },
  {
    id: "dispel_magic",
    name: "Dissipar Magia",
    level: 3,
    school: "Abjuração",
    castingTime: "action",
    range: "36 metros",
    components: "V, S",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Escolha uma criatura, objeto ou efeito mágico. Qualquer magia de nível 3 ou inferior no alvo é encerrada. Para magias superiores, faça um teste do seu atributo (CD = 10 + nível da magia).",
    effect: "utility",
    targetType: "single"
  },
  {
    id: "fly",
    name: "Voar",
    level: 3,
    school: "Transmutação",
    castingTime: "action",
    range: "Toque",
    components: "V, S, M",
    duration: "10 minutos",
    isConcentration: true,
    isRitual: false,
    description: "Você toca uma criatura. Ela ganha deslocamento de voo de 18m pelo tempo da duração.",
    effect: "buff",
    targetType: "single"
  },
  {
    id: "haste",
    name: "Velocidade",
    level: 3,
    school: "Transmutação",
    castingTime: "action",
    range: "9 metros",
    components: "V, S, M",
    duration: "1 minuto",
    isConcentration: true,
    isRitual: false,
    description: "O alvo ganha +2 de CA, vantagem em salvaguardas de DES, o dobro do deslocamento e uma ação extra por turno (apenas para Atacar 1 vez, Disparar, Desengajar, Esconder ou Usar Objeto).",
    effect: "buff",
    targetType: "single"
  },
  {
    id: "slow",
    name: "Lentidão",
    level: 3,
    school: "Transmutação",
    castingTime: "action",
    range: "36 metros",
    components: "V, S, M",
    duration: "1 minuto",
    isConcentration: true,
    isRitual: false,
    description: "Altera o tempo num cubo de 12m. Teste de SAB. Na falha, sofre -2 de CA, -2 DES, deslocamento cai pela metade e não pode ter reações ou múltiplos ataques.",
    effect: "debuff",
    targetType: "area",
    savingThrow: "sab"
  },
  {
    id: "revivify",
    name: "Reviver",
    level: 3,
    school: "Necromancia",
    castingTime: "action",
    range: "Toque",
    components: "V, S, M",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Você toca uma criatura que tenha morrido no último minuto. A criatura volta à vida com 1 ponto de vida.",
    effect: "heal",
    targetType: "single"
  },
  {
    id: "hypnotic_pattern",
    name: "Padrão Hipnótico",
    level: 3,
    school: "Ilusão",
    castingTime: "action",
    range: "36 metros",
    components: "S, M",
    duration: "1 minuto",
    isConcentration: true,
    isRitual: false,
    description: "Cores num cubo de 9m. Teste de SAB. Na falha, a criatura fica Enfeitiçada, Incapacitada e com deslocamento 0 enquanto você concentrar.",
    effect: "debuff",
    targetType: "area",
    savingThrow: "sab"
  },
  {
    id: "fear",
    name: "Medo",
    level: 3,
    school: "Ilusão",
    castingTime: "action",
    range: "Pessoal (Cone 9m)",
    components: "V, S, M",
    duration: "1 minuto",
    isConcentration: true,
    isRitual: false,
    description: "Projeta uma imagem apavorante num cone de 9m. Teste de SAB ou fica Amedrontada e deve largar o que segura e fugir de você.",
    effect: "debuff",
    targetType: "area",
    savingThrow: "sab"
  },
  {
    id: "fireball",
    name: "Bola de Fogo",
    level: 3,
    school: "Evocação",
    castingTime: "action",
    range: "45 metros",
    components: "V, S, M",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Uma explosão de fogo em uma esfera de 6m de raio. Cada criatura deve fazer um Teste de Resistência de Destreza. Uma criatura sofre 8d6 de dano de fogo em uma falha, ou metade se passar.",
    damageDice: "8d6",
    damageType: "fogo",
    savingThrow: "des",
    effect: "damage",
    targetType: "area"
  },
  
  // NÍVEL 4
  {
    id: "polymorph",
    name: "Polimorfo",
    level: 4,
    school: "Transmutação",
    castingTime: "action",
    range: "18 metros",
    components: "V, S, M",
    duration: "1 hora",
    isConcentration: true,
    isRitual: false,
    description: "Transforma uma criatura que você possa ver dentro do alcance em uma nova forma. Um alvo involuntário deve ser bem sucedido em um teste de SAB.",
    savingThrow: "sab",
    effect: "utility",
    targetType: "single"
  },

  // NÍVEL 5
  {
    id: "cone_of_cold",
    name: "Cone de Frio",
    level: 5,
    school: "Evocação",
    castingTime: "action",
    range: "Pessoal (Cone 18m)",
    components: "V, S, M",
    duration: "Instantânea",
    isConcentration: false,
    isRitual: false,
    description: "Uma explosão de ar frio entra em erupção de suas mãos. Cada criatura em um cone de 18 metros deve fazer um Teste de Resistência de CON, sofrendo 8d8 dano de frio na falha.",
    damageDice: "8d8",
    damageType: "frio",
    savingThrow: "con",
    effect: "damage",
    targetType: "area"
  }
];
