import { Npc, Player } from '../gameData';

export function mapNpcToDB(npc: Npc, campaignId: string) {
  return {
    id: npc.id,
    campaign_id: campaignId,
    name: npc.name || '',
    title: npc.title || '',
    faction: npc.faction || '',
    race: npc.race || '',
    alignment: npc.alignment || '',
    cr: String(npc.cr || ''),
    str: Number(npc.str || 10),
    dex: Number(npc.dex || 10),
    con: Number(npc.con || 10),
    int: Number(npc.int || 10),
    wis: Number(npc.wis || 10),
    cha: Number(npc.cha || 10),
    hp_max: Number(npc.hpMax || 0),
    hp_current: Number(npc.hpCurrent || 0),
    ac: String(npc.ac || ''),
    initiative: npc.init || '',
    speed: npc.speed || '',
    perception: String(npc.perc || ''),
    main_attack: npc.mainAttack || '',
    resistances: npc.res || '',
    immunities: npc.imm || '',
    actions: npc.actions || '',
    motivation: npc.mot || '',
    secrets: npc.sec || '',
    traits: npc.traits || '',
    items_visible: npc.itemsVis || '',
    items_hidden: npc.itemsHid || '',
    notes: npc.notes || '',
    has_spells: npc.hasSpells || false,
    spell_slots: npc.spellSlots || {},
    spell_slots_used: npc.spellSlotsUsed || {},
    is_dead: npc.isDead || false,
    is_hidden: npc.isHidden || false,
    image_url: npc.image || null,
    transformation: npc.transformation || null,
    is_transformed: npc.isTransformed || false
  };
}

export function mapDBToNpc(row: any): Npc {
  return {
    id: row.id,
    name: row.name,
    title: row.title,
    faction: row.faction,
    race: row.race,
    alignment: row.alignment,
    cr: row.cr,
    str: row.str,
    dex: row.dex,
    con: row.con,
    int: row.int,
    wis: row.wis,
    cha: row.cha,
    hpMax: row.hp_max,
    hpCurrent: row.hp_current,
    ac: row.ac,
    init: row.initiative,
    speed: row.speed,
    perc: row.perception,
    mainAttack: row.main_attack,
    res: row.resistances,
    imm: row.immunities,
    actions: row.actions,
    mot: row.motivation,
    sec: row.secrets,
    traits: row.traits,
    itemsVis: row.items_visible,
    itemsHid: row.items_hidden,
    notes: row.notes,
    hasSpells: row.has_spells,
    spellSlots: row.spell_slots || {},
    spellSlotsUsed: row.spell_slots_used || {},
    isDead: row.is_dead,
    isHidden: row.is_hidden,
    image: row.image_url,
    transformation: row.transformation,
    isTransformed: row.is_transformed || false
  };
}

export function mapPlayerToDB(player: Player, campaignId: string) {
  return {
    id: player.id,
    campaign_id: campaignId,
    name: player.name || '',
    player_name: player.playerName || '',
    player_class: player.playerClass || '',
    player_level: player.playerLevel || 1,
    class_level: player.classLevel || '',
    race: player.race || '',
    str: Number(player.str || 10),
    dex: Number(player.dex || 10),
    con: Number(player.con || 10),
    int: Number(player.int || 10),
    wis: Number(player.wis || 10),
    cha: Number(player.cha || 10),
    hp_max: Number(player.hpMax || 0),
    hp_current: Number(player.hpCurrent || 0),
    ac: String(player.ac || ''),
    initiative: player.init || '',
    speed: player.speed || '',
    perception: String(player.perc || ''),
    hd_total: player.hdTotal || '',
    prof_bonus: player.profBonus || '',
    inspiration: player.inspiration || false,
    saves: player.saves || [],
    skills: player.skills || [],
    attacks: player.attacks || [],
    image_url: player.image || null,
    is_dead: player.isDead || false,
    is_sleeping_action: player.isSleepingAction || false,
    exhaustion_level: player.exhaustionLevel || 0,
    min_sleep_req: player.minSleepReq || 8,
    transformation: player.transformation || null,
    is_transformed: player.isTransformed || false
  };
}

export function mapDBToPlayer(row: any): Player {
  return {
    id: row.id,
    name: row.name,
    playerName: row.player_name,
    playerClass: row.player_class,
    playerLevel: row.player_level,
    classLevel: row.class_level,
    race: row.race,
    str: row.str,
    dex: row.dex,
    con: row.con,
    int: row.int,
    wis: row.wis,
    cha: row.cha,
    hpMax: row.hp_max,
    hpCurrent: row.hp_current,
    ac: row.ac,
    init: row.initiative,
    speed: row.speed,
    perc: row.perception,
    hdTotal: row.hd_total,
    profBonus: row.prof_bonus,
    inspiration: row.inspiration,
    saves: row.saves || [],
    skills: row.skills || [],
    attacks: row.attacks || [],
    image: row.image_url,
    isDead: row.is_dead,
    isSleepingAction: row.is_sleeping_action,
    exhaustionLevel: row.exhaustion_level,
    minSleepReq: row.min_sleep_req || 8,
    transformation: row.transformation,
    isTransformed: row.is_transformed || false
  };
}
