import { Npc, Player } from '../gameData';

const isValidUUID = (str: string) => /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(str);

export function mapNpcToDB(npc: Npc, campaignId: string) {
  return {
    id: (npc.id && isValidUUID(npc.id)) ? npc.id : crypto.randomUUID(),
    campaign_id: campaignId,
    name: npc.name || '',
    title: npc.title || '',
    faction: npc.faction || '',
    race: npc.race || '',
    alignment: npc.alignment || '',
    cr: String(npc.cr || ''),
    str: Number(npc.str || 10),
    dex: Number(npc.dex || 10),
    con: Number(npc.con || 10),
    int: Number(npc.int || 10),
    wis: Number(npc.wis || 10),
    cha: Number(npc.cha || 10),
    hp_max: Number(npc.hpMax || 0),
    hp_current: Number(npc.hpCurrent || 0),
    ac: String(npc.ac || ''),
    initiative: npc.init || '',
    speed: npc.speed || '',
    perception: String(npc.perc || ''),
    main_attack: npc.mainAttack || '',
    resistances: npc.res || '',
    immunities: npc.imm || '',
    actions: npc.actions || '',
    motivation: npc.mot || '',
    secrets: npc.sec || '',
    traits: npc.traits || '',
    items_visible: npc.itemsVis || '',
    items_hidden: npc.itemsHid || '',
    notes: npc.notes || '',
    has_spells: npc.hasSpells || false,
    spell_slots: npc.spellSlots || {},
    spell_slots_used: npc.spellSlotsUsed || {},
    is_dead: npc.isDead || false,
    is_hidden: npc.isHidden || false,
    image_url: npc.image || null,
    transformation: npc.transformation || null,
    is_transformed: npc.isTransformed || false,
    spellcasting_ability: (npc.spellcastingAbility === 'none' ? 'int' : npc.spellcastingAbility) || 'int',
    spell_slot_type: npc.spellSlotType || 'standard',
    spells_known: npc.spellsKnown || [],
    class_resources: npc.classResources || [],
    attacks: npc.attacks || [],
    player_class: npc.playerClass || '',
    player_level: npc.playerLevel || 1,
    custom_class: (npc.playerClass !== 'custom' && npc.subclass) ? npc.subclass : (npc.customClass || ''),
    expertise_skills: npc.expertiseSkills || [],
    temp_hp: npc.tempHp || 0,
    temp_ac: npc.tempAc || 0,
    temp_res: npc.tempRes || [],
    conditions: npc.conditions || [],
    active_buffs: npc.activeBuffs || [],
    saves: npc.saves || [],
    prof_bonus: npc.profBonus || '',
    abilities: npc.abilities || [],
    resistances_arr: npc.resistances || [],
    immunities_arr: npc.immunities || [],
    multiattack_count: npc.multiattackCount || 1
  };
}

export function mapDBToNpc(row: any): Npc {
  return {
    id: row.id,
    name: row.name,
    title: row.title,
    faction: row.faction,
    race: row.race,
    alignment: row.alignment,
    cr: row.cr,
    str: row.str,
    dex: row.dex,
    con: row.con,
    int: row.int,
    wis: row.wis,
    cha: row.cha,
    hpMax: row.hp_max,
    hpCurrent: row.hp_current,
    ac: row.ac,
    init: row.initiative,
    speed: row.speed,
    perc: row.perception,
    mainAttack: row.main_attack,
    res: row.resistances,
    imm: row.immunities,
    actions: row.actions,
    mot: row.motivation,
    sec: row.secrets,
    traits: row.traits,
    itemsVis: row.items_visible,
    itemsHid: row.items_hidden,
    notes: row.notes,
    hasSpells: row.has_spells,
    spellSlots: row.spell_slots || {},
    spellSlotsUsed: row.spell_slots_used || {},
    spellcastingAbility: row.spellcasting_ability || 'int',
    spellSlotType: row.spell_slot_type || 'standard',
    spellsKnown: row.spells_known || [],
    classResources: row.class_resources || [],
    attacks: row.attacks || [],
    playerClass: row.player_class || '',
    playerLevel: row.player_level || 1,
    customClass: row.player_class === 'custom' ? (row.custom_class || '') : '',
    subclass: row.player_class !== 'custom' ? (row.custom_class || '') : '',
    expertiseSkills: row.expertise_skills || [],
    isDead: row.is_dead,
    isHidden: row.is_hidden,
    image: row.image_url,
    transformation: row.transformation,
    isTransformed: row.is_transformed || false,
    tempHp: row.temp_hp || 0,
    tempAc: row.temp_ac || 0,
    tempRes: row.temp_res || [],
    conditions: row.conditions || [],
    activeBuffs: row.active_buffs || [],
    saves: row.saves || [],
    profBonus: row.prof_bonus || '',
    abilities: row.abilities || [],
    resistances: row.resistances_arr || [],
    immunities: row.immunities_arr || [],
    multiattackCount: row.multiattack_count || 1
  };
}

export function mapPlayerToDB(player: Player, campaignId: string) {
  return {
    id: (player.id && isValidUUID(player.id)) ? player.id : crypto.randomUUID(),
    campaign_id: campaignId,
    name: player.name || 'Desconhecido',
    player_name: player.playerName || '',
    player_class: player.playerClass || 'N/A',
    player_level: player.playerLevel || 1,
    class_level: player.classLevel || 'N/A',
    class: player.playerClass || 'N/A',
    race: player.race || '',
    str: Number(player.str || 10),
    dex: Number(player.dex || 10),
    con: Number(player.con || 10),
    int: Number(player.int || 10),
    wis: Number(player.wis || 10),
    cha: Number(player.cha || 10),
    hp_max: Number(player.hpMax || 0),
    hp_current: Number(player.hpCurrent || 0),
    ac: String(player.ac || ''),
    initiative: player.init || '',
    speed: player.speed || '',
    perception: String(player.perc || ''),
    hd_total: player.hdTotal || '',
    prof_bonus: player.profBonus || '',
    inspiration: player.inspiration || false,
    saves: player.saves || [],
    skills: player.skills || [],
    attacks: player.attacks || [],
    image_url: player.image || null,
    is_dead: player.isDead || false,
    is_sleeping_action: player.isSleepingAction || false,
    exhaustion_level: player.exhaustionLevel || 0,
    min_sleep_req: player.minSleepReq || 8,
    transformation: player.transformation || null,
    is_transformed: player.isTransformed || false,
    inventory: player.inventory || [],
    notes: player.notes || '',
    background: player.background || '',
    personal_goals: player.personalGoals || '',
    temp_hp: player.tempHp || 0,
    conditions: player.conditions || [],
    active_buffs: player.activeBuffs || [],
    sleep_hours_today: player.sleepHoursToday || 0,
    has_spells: player.hasSpells || false,
    spellcasting_ability: (player.spellcastingAbility === 'none' ? 'int' : player.spellcastingAbility) || 'int',
    spell_slot_type: player.spellSlotType || 'standard',
    spell_slots: player.spellSlots || {},
    spell_slots_used: player.spellSlotsUsed || {},
    spells_known: player.spellsKnown || [],
    class_resources: player.classResources || [],
    expertise_skills: player.expertiseSkills || [],
    custom_class: (player.playerClass !== 'custom' && player.subclass) ? player.subclass : (player.customClass || ''),
    short_rest_taken_today: player.shortRestTakenToday || false,
    abilities: player.abilities || [],
    resistances_arr: player.resistances || [],
    immunities_arr: player.immunities || []
  };
}

export function mapDBToPlayer(row: any): Player {
  return {
    id: row.id,
    name: row.name,
    playerName: row.player_name,
    playerClass: row.player_class || row.class,
    playerLevel: row.player_level,
    classLevel: row.class_level,
    race: row.race,
    str: row.str,
    dex: row.dex,
    con: row.con,
    int: row.int,
    wis: row.wis,
    cha: row.cha,
    hpMax: row.hp_max,
    hpCurrent: row.hp_current,
    ac: row.ac,
    init: row.initiative,
    speed: row.speed,
    perc: row.perception,
    hdTotal: row.hd_total,
    profBonus: row.prof_bonus,
    inspiration: row.inspiration,
    saves: row.saves || [],
    skills: row.skills || [],
    attacks: row.attacks || [],
    image: row.image_url,
    isDead: row.is_dead,
    isSleepingAction: row.is_sleeping_action,
    exhaustionLevel: row.exhaustion_level,
    minSleepReq: row.min_sleep_req || 8,
    transformation: row.transformation,
    isTransformed: row.is_transformed || false,
    inventory: row.inventory || [],
    notes: row.notes || '',
    background: row.background || '',
    personalGoals: row.personal_goals || '',
    tempHp: row.temp_hp || 0,
    conditions: row.conditions || [],
    activeBuffs: row.active_buffs || [],
    sleepHoursToday: row.sleep_hours_today || 0,
    hasSpells: row.has_spells || false,
    spellcastingAbility: row.spellcasting_ability || 'int',
    spellSlotType: row.spell_slot_type || 'standard',
    spellSlots: row.spell_slots || {},
    spellSlotsUsed: row.spell_slots_used || {},
    spellsKnown: row.spells_known || [],
    classResources: row.class_resources || [],
    expertiseSkills: row.expertise_skills || [],
    customClass: row.player_class === 'custom' ? (row.custom_class || '') : '',
    subclass: row.player_class !== 'custom' ? (row.custom_class || '') : '',
    shortRestTakenToday: row.short_rest_taken_today || false,
    abilities: row.abilities || [],
    resistances: row.resistances_arr || [],
    immunities: row.immunities_arr || []
  };
}
